2024-01-19 03:50:38,676 : INFO : Start of Training
2024-01-19 03:50:38,677 : INFO : Run_id: 2024-01-19_035038_341090233
2024-01-19 03:50:38,677 : INFO : Start of Data Load, validation and transformation...
2024-01-19 03:50:38,677 : INFO : Start of Archiving Old Rejected Files...
2024-01-19 03:50:38,678 : INFO : End of Archiving Old Rejected Files...
2024-01-19 03:50:38,678 : INFO : Start of Archiving Old Validated Files...
2024-01-19 03:50:38,678 : INFO : End of Archiving Old Validated Files...
2024-01-19 03:50:38,678 : INFO : Start of Archiving Old Processed Files...
2024-01-19 03:50:38,678 : INFO : End of Archiving Old Processed Files...
2024-01-19 03:50:38,678 : INFO : Start of Archiving Old Result Files...
2024-01-19 03:50:38,678 : INFO : End of Archiving Old Result Files...
2024-01-19 03:50:38,678 : INFO : Start of Reading values From Schema...
2024-01-19 03:50:38,678 : INFO : End of Reading values From Schema...
2024-01-19 03:50:38,678 : INFO : Start of Validating Column Length...
2024-01-19 03:50:38,678 : INFO : End of Validating column Length
2024-01-19 03:50:38,678 : INFO : Start of Validating Missing Values...
2024-01-19 03:50:38,678 : INFO : End of Validating Missing Values
2024-01-19 03:50:38,678 : INFO : Start of Replacing Missing Values with NULL...
2024-01-19 03:50:38,678 : INFO : End of Replacing Missing Values with NULL...
2024-01-19 03:50:38,678 : INFO : Start of Creating Table...
2024-01-19 03:50:38,679 : INFO : Opened training database successfully
2024-01-19 03:50:38,679 : INFO : Tables created successfully
2024-01-19 03:50:38,679 : INFO : Closed training database successfully
2024-01-19 03:50:38,679 : INFO : End of Creating Table...
2024-01-19 03:50:38,679 : INFO : Opened training database successfully
2024-01-19 03:50:38,679 : INFO : Start of Inserting Data into Table...
2024-01-19 03:50:38,679 : INFO : End of Inserting Data into Table...
2024-01-19 03:50:38,679 : INFO : Start of Exporting Data into CSV...
2024-01-19 03:50:38,681 : INFO : Opened training database successfully
2024-01-19 03:50:38,843 : INFO : End of Exporting Data into CSV...
2024-01-19 03:50:38,845 : INFO : Start of Moving Processed Files...
2024-01-19 03:50:38,845 : INFO : End of Moving Processed Files...
2024-01-19 03:50:38,845 : INFO : End of Data Load, validation and transformation
2024-01-19 03:50:38,845 : INFO : Start of Preprocessing...
2024-01-19 03:50:38,845 : INFO : Start of Reading dataset...
2024-01-19 03:50:38,872 : INFO : End of reading dataset...
2024-01-19 03:50:38,872 : INFO : Start of Droping columns...
2024-01-19 03:50:38,873 : INFO : End of Droping columns...
2024-01-19 03:50:38,873 : INFO : Start of feature encoding...
2024-01-19 03:50:38,877 : INFO : End of feature encoding...
2024-01-19 03:50:38,878 : INFO : Start of Droping columns...
2024-01-19 03:50:38,879 : INFO : End of Droping columns...
2024-01-19 03:50:38,879 : INFO : Start of finding missing values...
2024-01-19 03:50:38,891 : INFO : Start of finding missing values...
2024-01-19 03:50:38,891 : INFO : Start of Imputing missing values...
2024-01-19 03:50:38,957 : INFO : End of Imputing missing values...
2024-01-19 03:50:38,957 : INFO : Start of splitting features and label...
2024-01-19 03:50:38,958 : INFO : End of splitting features and label...
2024-01-19 03:50:38,959 : INFO : End of Preprocessing...
2024-01-19 03:50:38,960 : INFO : Start of elbow plotting...
2024-01-19 03:50:54,770 : INFO : The optimum number of clusters is: 3
2024-01-19 03:50:54,770 : INFO : End of elbow plotting...
2024-01-19 03:50:54,770 : INFO : Start of Create clusters...
2024-01-19 03:50:56,362 : INFO : Start of Save Models
2024-01-19 03:50:56,362 : INFO : Start of Save Models
2024-01-19 03:50:56,368 : INFO : Model File KMeans saved
2024-01-19 03:50:56,368 : INFO : Model File KMeans saved
2024-01-19 03:50:56,369 : INFO : End of Save Models
2024-01-19 03:50:56,369 : INFO : End of Save Models
2024-01-19 03:50:56,371 : INFO : succesfully created 3 clusters.
2024-01-19 03:50:56,371 : INFO : End of Create clusters...
2024-01-19 03:50:56,373 : INFO : Start of finding best model...
2024-01-19 03:50:56,373 : INFO : Start of finding best params for XGBoost algo...
2024-01-19 03:51:08,888 : INFO : XGBoost best params: {'learning_rate': 0.5, 'max_depth': 10, 'n_estimators': 100}
2024-01-19 03:51:08,888 : INFO : End of finding best params for XGBoost algo...
2024-01-19 03:51:08,923 : INFO : AUC for XGBoost:0.9842440647602135
2024-01-19 03:51:08,923 : INFO : Start of finding best params for randomforest algo...
2024-01-19 03:51:19,506 : INFO : Random Forest best params: {'criterion': 'entropy', 'max_depth': 3, 'max_features': 'log2', 'n_estimators': 130}
2024-01-19 03:51:19,506 : INFO : End of finding best params for randomforest algo...
2024-01-19 03:51:19,519 : ERROR : Exception raised while finding best model:'ModelTuner' object has no attribute 'random_fores_score'
Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 166, in get_best_model
    self.logger.info('AUC for Random Fores:'+str(self.random_fores_score))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelTuner' object has no attribute 'random_fores_score'
2024-01-19 03:51:19,520 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 166, in get_best_model
    self.logger.info('AUC for Random Fores:'+str(self.random_fores_score))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelTuner' object has no attribute 'random_fores_score'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/training/train_model.py", line 84, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 176, in get_best_model
    raise Exception()
Exception
