2024-01-19 03:52:52,527 : INFO : Start of Training
2024-01-19 03:52:52,527 : INFO : Run_id: 2024-01-19_035252_143083734
2024-01-19 03:52:52,527 : INFO : Start of Data Load, validation and transformation...
2024-01-19 03:52:52,527 : INFO : Start of Archiving Old Rejected Files...
2024-01-19 03:52:52,527 : INFO : End of Archiving Old Rejected Files...
2024-01-19 03:52:52,527 : INFO : Start of Archiving Old Validated Files...
2024-01-19 03:52:52,527 : INFO : End of Archiving Old Validated Files...
2024-01-19 03:52:52,527 : INFO : Start of Archiving Old Processed Files...
2024-01-19 03:52:52,527 : INFO : End of Archiving Old Processed Files...
2024-01-19 03:52:52,527 : INFO : Start of Archiving Old Result Files...
2024-01-19 03:52:52,527 : INFO : End of Archiving Old Result Files...
2024-01-19 03:52:52,531 : INFO : Start of Reading values From Schema...
2024-01-19 03:52:52,531 : INFO : End of Reading values From Schema...
2024-01-19 03:52:52,531 : INFO : Start of Validating Column Length...
2024-01-19 03:52:52,531 : INFO : End of Validating column Length
2024-01-19 03:52:52,531 : INFO : Start of Validating Missing Values...
2024-01-19 03:52:52,531 : INFO : End of Validating Missing Values
2024-01-19 03:52:52,531 : INFO : Start of Replacing Missing Values with NULL...
2024-01-19 03:52:52,531 : INFO : End of Replacing Missing Values with NULL...
2024-01-19 03:52:52,531 : INFO : Start of Creating Table...
2024-01-19 03:52:52,531 : INFO : Opened training database successfully
2024-01-19 03:52:52,531 : INFO : Tables created successfully
2024-01-19 03:52:52,531 : INFO : Closed training database successfully
2024-01-19 03:52:52,532 : INFO : End of Creating Table...
2024-01-19 03:52:52,532 : INFO : Opened training database successfully
2024-01-19 03:52:52,532 : INFO : Start of Inserting Data into Table...
2024-01-19 03:52:52,532 : INFO : End of Inserting Data into Table...
2024-01-19 03:52:52,532 : INFO : Start of Exporting Data into CSV...
2024-01-19 03:52:52,532 : INFO : Opened training database successfully
2024-01-19 03:52:52,621 : INFO : End of Exporting Data into CSV...
2024-01-19 03:52:52,625 : INFO : Start of Moving Processed Files...
2024-01-19 03:52:52,625 : INFO : End of Moving Processed Files...
2024-01-19 03:52:52,625 : INFO : End of Data Load, validation and transformation
2024-01-19 03:52:52,625 : INFO : Start of Preprocessing...
2024-01-19 03:52:52,625 : INFO : Start of Reading dataset...
2024-01-19 03:52:52,639 : INFO : End of reading dataset...
2024-01-19 03:52:52,639 : INFO : Start of Droping columns...
2024-01-19 03:52:52,640 : INFO : End of Droping columns...
2024-01-19 03:52:52,640 : INFO : Start of feature encoding...
2024-01-19 03:52:52,642 : INFO : End of feature encoding...
2024-01-19 03:52:52,642 : INFO : Start of Droping columns...
2024-01-19 03:52:52,643 : INFO : End of Droping columns...
2024-01-19 03:52:52,643 : INFO : Start of finding missing values...
2024-01-19 03:52:52,658 : INFO : Start of finding missing values...
2024-01-19 03:52:52,658 : INFO : Start of Imputing missing values...
2024-01-19 03:52:52,683 : INFO : End of Imputing missing values...
2024-01-19 03:52:52,683 : INFO : Start of splitting features and label...
2024-01-19 03:52:52,683 : INFO : End of splitting features and label...
2024-01-19 03:52:52,683 : INFO : End of Preprocessing...
2024-01-19 03:52:52,685 : INFO : Start of elbow plotting...
2024-01-19 03:53:05,260 : INFO : The optimum number of clusters is: 3
2024-01-19 03:53:05,260 : INFO : End of elbow plotting...
2024-01-19 03:53:05,260 : INFO : Start of Create clusters...
2024-01-19 03:53:08,145 : INFO : Start of Save Models
2024-01-19 03:53:08,145 : INFO : Start of Save Models
2024-01-19 03:53:08,151 : INFO : Model File KMeans saved
2024-01-19 03:53:08,151 : INFO : Model File KMeans saved
2024-01-19 03:53:08,152 : INFO : End of Save Models
2024-01-19 03:53:08,152 : INFO : End of Save Models
2024-01-19 03:53:08,152 : INFO : succesfully created 3 clusters.
2024-01-19 03:53:08,152 : INFO : End of Create clusters...
2024-01-19 03:53:08,154 : INFO : Start of finding best model...
2024-01-19 03:53:08,154 : INFO : Start of finding best params for XGBoost algo...
2024-01-19 03:53:21,533 : INFO : XGBoost best params: {'learning_rate': 0.5, 'max_depth': 10, 'n_estimators': 100}
2024-01-19 03:53:21,534 : INFO : End of finding best params for XGBoost algo...
2024-01-19 03:53:21,537 : INFO : AUC for XGBoost:0.9842440647602135
2024-01-19 03:53:21,537 : INFO : Start of finding best params for randomforest algo...
2024-01-19 03:53:31,920 : INFO : Random Forest best params: {'criterion': 'gini', 'max_depth': 3, 'max_features': 'log2', 'n_estimators': 50}
2024-01-19 03:53:31,920 : INFO : End of finding best params for randomforest algo...
2024-01-19 03:53:31,929 : ERROR : Exception raised while finding best model:'ModelTuner' object has no attribute 'random_fores_score'
Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 166, in get_best_model
    self.logger.info('AUC for Random Forest:'+str(self.random_forest_score))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelTuner' object has no attribute 'random_fores_score'
2024-01-19 03:53:31,929 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 166, in get_best_model
    self.logger.info('AUC for Random Forest:'+str(self.random_forest_score))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelTuner' object has no attribute 'random_fores_score'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/training/train_model.py", line 84, in training_model
    best_model_name, best_model = self.modelTuner.get_best_model(x_train, y_train, x_test, y_test)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/draeghonvm/Projects/Supervised_ML_Project/apps/tuning/model_tuner.py", line 176, in get_best_model
    raise Exception()
Exception
